// lib/menu-text.ts
// Every word the public menu says, in the two guest languages. It lives apart from the shapes and
// the vocabulary in `lib/menu.ts` because it is a different kind of thing and grows on its own
// schedule: a dish gaining a state (sold out) adds a string here, not a type there, and the two
// used to share one module until it reached its size budget saying so.
import type { Locale } from './menu'

/** UI strings for the customer pages. Restaurant content is bilingual in the data; this covers the chrome. */
export const MENU_TEXT = {
  en: {
    search: 'Search menu',
    filters: 'Filters',
    ar: 'AR',
    photo: 'Photo',
    model3d: '3D',
    view3d: 'View in 3D',
    viewPhoto: 'View the photo',
    arOnly: 'Show only dishes with AR',
    dietary: 'Dietary',
    clear: 'Clear filters',
    done: 'Done',
    noResults: 'No dishes match',
    noResultsHint: 'Try another word or clear the filters.',
    seeOnTable: 'See it on your table',
    openingAR: 'Opening AR…',
    ingredients: 'Ingredients',
    contains: 'Contains',
    kcal: 'kcal',
    popular: 'Popular',
    soldOut: 'Sold out today',
    backToMenu: 'Back to menu',
    share: 'Share',
    linkCopied: 'Link copied',
    dishes: 'dishes',
    dish: 'dish',
    hours: 'Opening hours',
    contact: 'Contact',
    follow: 'Follow',
    directions: 'Directions',
    poweredBy: 'Menu by',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    openNow: 'Open',
    closedNow: 'Closed',
    closes: 'closes',
    opens: 'opens',
    skipToMenu: 'Skip to menu',
    categories: 'Categories',
    results: (n: number) => (n === 1 ? '1 dish matches' : `${n} dishes match`),
    shareMenu: 'Share this menu',
    install: 'Add to home screen',
    installHint: 'Opens like an app, works without signal.',
    offline: 'You are offline — showing the menu as it was last loaded.',
    menuOf: (name: string) => `Menu of ${name}`,
    installIos: 'On iPhone: tap Share, then “Add to Home Screen”.',
    offlineReady: 'Saved on this device — opens without signal.',
    updateAvailable: 'This menu has been updated.',
    refresh: 'Refresh',
    addToOrder: 'Add to order',
    add: (name: string) => `Add ${name}`,
    oneLess: (name: string) => `One less ${name}`,
    oneMore: (name: string) => `One more ${name}`,
    quantityOf: (name: string) => `Quantity of ${name}`,
    inOrder: (n: number) => `${n} in your order`,
    remove: (name: string) => `Remove ${name}`,
    addNote: 'Add a note',
    noteFor: (name: string) => `Note for ${name}`,
    notePlaceholder: 'No onions, well done…',
    saveNote: 'Done',
    viewOrder: 'View order',
    yourOrder: 'Your order',
    items: (n: number) => (n === 1 ? '1 item' : `${n} items`),
    emptyOrder: 'Nothing in your order yet. Add dishes from the menu.',
    subtotal: 'Subtotal',
    tableNumber: 'Table number',
    tableHint: 'Written on your table or on the QR code.',
    tableFromQr: 'From the QR code on your table.',
    phoneNumber: 'Phone number',
    phoneHint: 'We text you the confirmation of your order.',
    phoneRequired: 'Enter a phone number we can text.',
    orderNote: 'Note for the kitchen (optional)',
    placeOrder: 'Place order',
    sendingOrder: 'Sending…',
    orderSent: (n: number) => `Order #${n} sent`,
    orderSentHint: (table: string) => `The kitchen has it and will bring it to table ${table}.`,
    orderFailed: 'The order could not be sent. Check your connection and try again.',
    orderingOff: 'This restaurant is not taking orders right now.',
    menuChanged: 'The menu has changed since you picked a dish. Check your order and try again.',
    tableRequired: 'Enter your table number.',
  },
  fr: {
    search: 'Rechercher',
    filters: 'Filtres',
    ar: 'RA',
    photo: 'Photo',
    model3d: '3D',
    view3d: 'Voir en 3D',
    viewPhoto: 'Voir la photo',
    arOnly: 'Afficher uniquement les plats en RA',
    dietary: 'Régime',
    clear: 'Effacer les filtres',
    done: 'OK',
    noResults: 'Aucun plat ne correspond',
    noResultsHint: 'Essayez un autre mot ou effacez les filtres.',
    seeOnTable: 'Voir sur votre table',
    openingAR: 'Ouverture de la RA…',
    ingredients: 'Ingrédients',
    contains: 'Contient',
    kcal: 'kcal',
    popular: 'Populaire',
    soldOut: "Plus disponible aujourd'hui",
    backToMenu: 'Retour au menu',
    share: 'Partager',
    linkCopied: 'Lien copié',
    dishes: 'plats',
    dish: 'plat',
    hours: "Horaires d'ouverture",
    contact: 'Contact',
    follow: 'Suivre',
    directions: 'Itinéraire',
    poweredBy: 'Menu par',
    lightMode: 'Mode clair',
    darkMode: 'Mode sombre',
    openNow: 'Ouvert',
    closedNow: 'Fermé',
    closes: 'ferme à',
    opens: 'ouvre à',
    skipToMenu: 'Aller au menu',
    categories: 'Catégories',
    results: (n: number) => (n === 1 ? '1 plat correspond' : `${n} plats correspondent`),
    shareMenu: 'Partager ce menu',
    install: 'Ajouter à l’écran d’accueil',
    installHint: 'S’ouvre comme une app, fonctionne sans réseau.',
    offline: 'Vous êtes hors ligne — menu affiché tel qu’il a été chargé.',
    menuOf: (name: string) => `Menu de ${name}`,
    installIos: 'Sur iPhone : touchez Partager, puis « Sur l’écran d’accueil ».',
    offlineReady: 'Enregistré sur cet appareil — s’ouvre sans réseau.',
    updateAvailable: 'Ce menu a été mis à jour.',
    refresh: 'Actualiser',
    addToOrder: 'Ajouter à la commande',
    add: (name: string) => `Ajouter ${name}`,
    oneLess: (name: string) => `Un ${name} de moins`,
    oneMore: (name: string) => `Un ${name} de plus`,
    quantityOf: (name: string) => `Quantité de ${name}`,
    inOrder: (n: number) => `${n} dans votre commande`,
    remove: (name: string) => `Retirer ${name}`,
    addNote: 'Ajouter une note',
    noteFor: (name: string) => `Note pour ${name}`,
    notePlaceholder: 'Sans oignons, bien cuit…',
    saveNote: 'OK',
    viewOrder: 'Voir la commande',
    yourOrder: 'Votre commande',
    items: (n: number) => (n === 1 ? '1 article' : `${n} articles`),
    emptyOrder: 'Rien dans votre commande pour l’instant. Ajoutez des plats depuis le menu.',
    subtotal: 'Sous-total',
    tableNumber: 'Numéro de table',
    tableHint: 'Indiqué sur votre table ou sur le QR code.',
    tableFromQr: 'Depuis le QR code de votre table.',
    phoneNumber: 'Numéro de téléphone',
    phoneHint: 'Nous vous envoyons la confirmation de votre commande par SMS.',
    phoneRequired: 'Indiquez un numéro de téléphone.',
    orderNote: 'Note pour la cuisine (facultatif)',
    placeOrder: 'Commander',
    sendingOrder: 'Envoi…',
    orderSent: (n: number) => `Commande n° ${n} envoyée`,
    orderSentHint: (table: string) => `La cuisine l’a reçue et l’apportera à la table ${table}.`,
    orderFailed: 'La commande n’a pas pu être envoyée. Vérifiez votre connexion et réessayez.',
    orderingOff: 'Ce restaurant ne prend pas de commandes pour le moment.',
    menuChanged: 'Le menu a changé depuis votre choix. Vérifiez votre commande et réessayez.',
    tableRequired: 'Indiquez votre numéro de table.',
  },
} as const satisfies Record<Locale, unknown>
